package me.tbsten.compose.preview.lab

/**
 * Provides a delegate that collects `@Preview` functions from **this module only**.
 *
 * The Compose Preview Lab compiler plugin replaces the body at compile time so that the returned
 * delegate holds the actual preview list. If the compiler plugin is not applied,
 * accessing the value throws an [IllegalStateException].
 *
 * The returned [PreviewExport] functions as a property delegate for a `List<CollectedPreview>`.
 * It wraps a [Lazy] so that `@Composable` lambdas inside [CollectedPreview] are initialized
 * on first access rather than at class-load time, avoiding `ExceptionInInitializerError`.
 * The same wrapper acts as a marker type that downstream modules pick up automatically —
 * see [collectAllModulePreviews].
 *
 * Example — single-module preview collection:
 * ```kotlin
 * val myPreviews by collectModulePreviews()
 * ```
 *
 * Example — used in a library module with public visibility:
 * ```kotlin
 * // uiLib/src/commonMain/kotlin/Previews.kt
 * val uiLibPreviews by collectModulePreviews()
 * ```
 *
 * @return a [PreviewExport] delegate wrapping the collected preview list; the body is replaced by the compiler plugin
 * @see collectAllModulePreviews
 */
@OptIn(InternalComposePreviewLabApi::class)
public fun collectModulePreviews(): PreviewExport = PreviewExport(
    lazy {
        error(
            "[ComposePreviewLab] collectModulePreviews() was not replaced by the compiler plugin. " +
                "Make sure the Compose Preview Lab compiler plugin is applied to this module.",
        )
    },
)

/**
 * Provides a delegate that collects `@Preview` functions from **this module and every
 * dependency module that has the Compose Preview Lab Gradle plugin applied**.
 *
 * The compiler plugin replaces the body at compile time so that the returned [PreviewExport]
 * holds a concatenation of this module's previews and the previews of every dependency module
 * on the classpath. Discovery is fully automatic — applying the Gradle plugin in a dependency
 * module is enough; **`collectModulePreviews()` does not need to be declared** there. Modules
 * that do declare it explicitly continue to work unchanged.
 *
 * **Cross-module aggregation works on every Compose Multiplatform target** (JVM / Android /
 * JS / Wasm JS / iOS) when running Kotlin 2.3.21 or later. The compiler plugin emits a
 * per-`@Preview` hint (`previewHint(value: PreviewHintMarker_<hash>?): CollectedPreview` in the
 * `me.tbsten.compose.preview.lab.hints` package) and the consumer side discovers them via
 * `IrPluginContext.referenceFunctions`, which works equally for JVM bytecode and KLIB modules.
 *
 * Older Kotlin (pre-2.3.21) does not support the FIR-based hint generator, so calling
 * `collectAllModulePreviews()` there fails at compile time with a clear upgrade-or-downgrade
 * message. `collectModulePreviews()` (single-module) continues to work on every Kotlin version.
 *
 * Example — app module aggregating its own previews and any library previews on the classpath:
 * ```kotlin
 * // app/src/commonMain/kotlin/Previews.kt
 * val appPreviews by collectAllModulePreviews()
 * ```
 *
 * Example — dependency module just applies the Gradle plugin; no `Previews.kt` file required:
 * ```kotlin
 * // uiLib/build.gradle.kts
 * plugins {
 *     id("me.tbsten.compose.preview.lab")
 * }
 * // any @Preview function in uiLib is now picked up by upstream collectAllModulePreviews()
 * ```
 *
 * @return a [PreviewExport] delegate wrapping the aggregated preview list; the body is replaced by the compiler plugin
 * @see collectModulePreviews
 */
@OptIn(InternalComposePreviewLabApi::class)
public fun collectAllModulePreviews(): PreviewExport = PreviewExport(
    lazy {
        error(
            "[ComposePreviewLab] collectAllModulePreviews() was not replaced by the compiler plugin. " +
                "Make sure the Compose Preview Lab compiler plugin is applied to this module.",
        )
    },
)

/**
 * Removes duplicates from the aggregated preview list by [CollectedPreview.id].
 *
 * Called from the IR generated by `collectAllModulePreviews()` to merge previews from this
 * module with previews discovered through the per-declaration hint mechanism
 * (`previewHint(value: PreviewHintMarker_<hash>?): CollectedPreview` functions). When a
 * dependency module also uses `collectAllModulePreviews()` (i.e. it re-exports its own
 * dependencies), the same `CollectedPreview` may reach the aggregator through more than one
 * hint chain. Deduplicating by `id` guarantees a stable result regardless of how many paths
 * a preview travels through.
 *
 * Internal API — meant only as a callsite for the compiler plugin.
 */
@InternalComposePreviewLabApi
public fun distinctPreviewsById(previews: List<CollectedPreview>): List<CollectedPreview> = previews.distinctBy { it.id }
