package me.tbsten.compose.preview.lab

/**
 * Provides a delegate that collects `@Preview` functions from **this module only**.
 *
 * The Compose Preview Lab compiler plugin replaces the body at compile time so that the returned
 * delegate holds the actual preview list. If the compiler plugin is not applied,
 * accessing the value throws an [IllegalStateException].
 *
 * The returned [PreviewExport] functions as a property delegate for a `List<CollectedPreview>`.
 * It wraps a [Lazy] so that `@Composable` lambdas inside [CollectedPreview] are initialized
 * on first access rather than at class-load time, avoiding `ExceptionInInitializerError`.
 * The same wrapper acts as a marker type that downstream modules pick up automatically —
 * see [collectAllModulePreviews].
 *
 * Example — single-module preview collection:
 * ```kotlin
 * val myPreviews by collectModulePreviews()
 * ```
 *
 * Example — used in a library module with public visibility:
 * ```kotlin
 * // uiLib/src/commonMain/kotlin/Previews.kt
 * val uiLibPreviews by collectModulePreviews()
 * ```
 *
 * @return a [PreviewExport] delegate wrapping the collected preview list; the body is replaced by the compiler plugin
 * @see collectAllModulePreviews
 */
@OptIn(InternalComposePreviewLabApi::class)
public fun collectModulePreviews(): PreviewExport = PreviewExport(
    lazy {
        error(
            "[ComposePreviewLab] collectModulePreviews() was not replaced by the compiler plugin. " +
                "Make sure the Compose Preview Lab compiler plugin is applied to this module.",
        )
    },
)

/**
 * Provides a delegate that collects `@Preview` functions from **this module and every
 * dependency module that has the Compose Preview Lab Gradle plugin applied**.
 *
 * The compiler plugin replaces the body at compile time so that the returned [PreviewExport]
 * holds a concatenation of this module's previews and the previews of every dependency module
 * on the classpath. Discovery is fully automatic — applying the Gradle plugin in a dependency
 * module is enough; **`collectModulePreviews()` does not need to be declared** there. Modules
 * that do declare it explicitly continue to work unchanged.
 *
 * **Cross-module aggregation works on every Compose Multiplatform target** (JVM / Android /
 * JS / Wasm JS / iOS) when running Kotlin 2.3.21 or later. The compiler plugin emits a
 * per-`@Preview` hint (`previewHint(value: PreviewHintMarker_<hash>?): CollectedPreview` in the
 * `me.tbsten.compose.preview.lab.hints` package) and the consumer side discovers them via
 * `IrPluginContext.referenceFunctions`, which works equally for JVM bytecode and KLIB modules.
 *
 * Older Kotlin (pre-2.3.21) does not support the FIR-based hint generator. The plugin's
 * IR pass detects the `val x by collectAllModulePreviews()` delegated-property pattern and
 * reports a compile-time error with a clear upgrade-or-downgrade message. Direct calls outside
 * a property delegate (which are not the supported usage) compile and fall back to the
 * `IllegalStateException` thrown by the placeholder body. `collectModulePreviews()`
 * (single-module) continues to work on every Kotlin version.
 *
 * Example — app module aggregating its own previews and any library previews on the classpath:
 * ```kotlin
 * // app/src/commonMain/kotlin/Previews.kt
 * val appPreviews by collectAllModulePreviews()
 * ```
 *
 * Example — dependency module just applies the Gradle plugin; no `Previews.kt` file required:
 * ```kotlin
 * // uiLib/build.gradle.kts
 * plugins {
 *     id("me.tbsten.compose.preview.lab")
 * }
 * // any @Preview function in uiLib is now picked up by upstream collectAllModulePreviews()
 * ```
 *
 * @return a [PreviewExport] delegate wrapping the aggregated preview list; the body is replaced by the compiler plugin
 * @see collectModulePreviews
 */
@OptIn(InternalComposePreviewLabApi::class)
public fun collectAllModulePreviews(): PreviewExport = PreviewExport(
    lazy {
        error(
            "[ComposePreviewLab] collectAllModulePreviews() was not replaced by the compiler plugin. " +
                "Make sure the Compose Preview Lab compiler plugin is applied to this module.",
        )
    },
)

/**
 * Removes duplicates from the aggregated preview list by [CollectedPreview.id], warning
 * via stdout when a duplicate is observed.
 *
 * Called from the IR generated by `collectAllModulePreviews()` to merge previews from this
 * module with previews discovered through the per-declaration hint mechanism
 * (`previewHint(value: PreviewHintMarker_<hash>?): CollectedPreview` functions). When a
 * dependency module also uses `collectAllModulePreviews()` (i.e. it re-exports its own
 * dependencies), the same `CollectedPreview` may reach the aggregator through more than
 * one hint chain. Deduplicating by `id` guarantees a stable result regardless of how many
 * paths a preview travels through.
 *
 * **Cross-artifact same-FQN previews surface here**: when two dependency modules declare
 * a `@Preview` with identical fully-qualified name (e.g. both expose
 * `com.example.SharedPreview()`), the FIR/IR generator produces a marker class with the
 * same `<canonical-key>` hash on both sides. The compiler / classloader resolves the
 * collision by picking one classfile non-deterministically — the **other** preview's
 * body is silently lost. The runtime can detect this only by observing duplicate
 * `CollectedPreview.id` values reaching this aggregator. We surface those duplicates as
 * a `println` line on stdout so users have a chance to notice ("why does my preview not
 * show up?") before chasing it through compiled artifacts. (`commonMain` has no portable
 * stderr API across all CMP targets, so stdout is intentional.) Resolution: **rename
 * the underlying `@Preview` function** in one of the colliding artifacts so its FQN no
 * longer matches. `@ComposePreviewLabOption(id = "...")` override does NOT help on any
 * platform: the FQN-based hint generator name collides at IR time before the override id
 * is read on JVM / Android, and on KLIB-based targets the linker further dedups by
 * IdSignature. Renaming the function is the only fix that works on every CMP target.
 *
 * Internal API — meant only as a callsite for the compiler plugin.
 */
@InternalComposePreviewLabApi
public fun distinctPreviewsById(previews: List<CollectedPreview>): List<CollectedPreview> {
    // Single-pass dedup: build the distinct list while detecting duplicates so we don't
    // walk `previews` twice (the previous `groupBy` + `distinctBy` combination allocated
    // a full `Map<String, List<CollectedPreview>>` only to drop most of it). `dupCounts`
    // only stores ids that actually duplicated, so the common no-collision path keeps
    // its map at zero entries.
    val seen = HashSet<String>(previews.size)
    val distinct = ArrayList<CollectedPreview>(previews.size)
    val dupCounts = HashMap<String, Int>()
    for (preview in previews) {
        if (seen.add(preview.id)) {
            distinct += preview
        } else {
            // Already seen once. The first collision records 2 (the originally-emitted
            // entry + this duplicate); each subsequent collision adds 1.
            val existing = dupCounts[preview.id]
            dupCounts[preview.id] = if (existing == null) 2 else existing + 1
        }
    }
    // stdout println keeps the runtime dependency-free (no logger framework) and works
    // across every CMP target without an expect/actual indirection. The warning fires
    // once per app launch even if the duplicated preview is never displayed, so users
    // see it during dev iteration.
    for ((id, count) in dupCounts) {
        println(
            "[ComposePreviewLab] WARNING: $count `CollectedPreview` entries share " +
                "id=\"$id\". Likely cause: a `@Preview` with the same fully-qualified name " +
                "is declared in two or more dependency artifacts on the classpath, so their " +
                "marker / hint classes collide and only one survives — the other preview's " +
                "body is unreachable. Resolution: rename the underlying `@Preview` function " +
                "in one of the artifacts so the FQN no longer collides. " +
                "(`@ComposePreviewLabOption(id = \"...\")` override does NOT help on any " +
                "CMP target: the FQN-based hint generator name collides at IR time before " +
                "the override id is read on JVM / Android, and on KLIB-based targets the " +
                "linker further dedups by IdSignature. Renaming the function is the only " +
                "portable fix.)",
        )
    }
    return distinct
}
