package me.tbsten.compose.preview.lab

import androidx.compose.runtime.Composable
import kotlin.js.ExperimentalJsExport
import me.tbsten.compose.preview.lab.util.JsOnlyExport
import me.tbsten.compose.preview.lab.util.JsOnlyExportIgnore

/**
 * `@Preview` information collected by the gradle plugin, passed to [PreviewLabGallery] to
 * render a catalog.
 *
 * ```kt
 * // generated by gradle plugin
 * package myApp
 * object PreviewList : List<CollectedPreview> by listOf(...)
 *
 * // user code
 * fun MyAppEntryPoint() {
 *   ComposePreviewLabGallery(previewList = myApp.PreviewList)
 * }
 * ```
 *
 * Construct manually via the [PreviewLabPreview] factory below to represent a pseudo-preview
 * not picked up by the gradle plugin (e.g. a one-off composition driven by user input):
 *
 * ```kt
 * ComposePreviewLabGallery(
 *   previews = myAppPreviews + listOf(
 *     CollectedPreview(
 *       displayName = "MyButtonPreview",
 *       filePath = "myApp/src/main/kotlin/myApp/MyButtonPreview.kt",
 *       startLineNumber = 10,
 *       code = null,
 *     ) { MyButton(text = fieldValue { StringField("Click!") }) },
 *   ),
 * )
 * ```
 *
 * @property startLineNumber 1-based.
 * @property endLineNumber 1-based, **inclusive**.
 * @property content Composable body of the preview; invoke to render it.
 *
 * @see CollectedPreview
 */
interface PreviewLabPreview {
    val id: String
    val displayName: String
    val filePath: String?
    val startLineNumber: Int?
    val endLineNumber: Int?
    val code: String?
    val kdoc: String?
    val content: @Composable () -> Unit
}

@OptIn(InternalComposePreviewLabApi::class, ExperimentalJsExport::class)
@JsOnlyExport
data class CollectedPreview @JsOnlyExportIgnore constructor(
    override val id: String,
    override val displayName: String = id,
    override val filePath: String? = null,
    override val startLineNumber: Int? = null,
    override val endLineNumber: Int? = null,
    override val code: String? = null,
    override val kdoc: String? = null,
    override val content: @Composable () -> Unit,
) : PreviewLabPreview

/**
 * Manual factory equivalent to [CollectedPreview] for callers that need to build a
 * preview outside the gradle-plugin-collected list. See [PreviewLabPreview] for the
 * property contract.
 */
fun PreviewLabPreview(
    id: String,
    displayName: String = id,
    filePath: String? = null,
    startLineNumber: Int? = null,
    endLineNumber: Int? = null,
    code: String? = null,
    kdoc: String? = null,
    content: @Composable () -> Unit,
): PreviewLabPreview = object : PreviewLabPreview {
    override val id: String = id
    override val displayName: String = displayName
    override val filePath: String? = filePath
    override val startLineNumber: Int? = startLineNumber
    override val endLineNumber: Int? = endLineNumber
    override val code: String? = code
    override val kdoc: String? = kdoc
    override val content: @Composable (() -> Unit) = content
}
