plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.ksp)
    id("me.tbsten.compose.preview.lab")
}

kotlin {
    jvmToolchain(17)

    jvm()

    js {
        browser()
        binaries.library()
        binaries.executable()
        generateTypeScriptDefinitions()

        compilerOptions {
            target = "es2015"
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.composeRuntime)
            implementation(libs.composeFoundation)
            implementation(libs.composeMaterial3)
            implementation(libs.composeUiToolingPreview)
            implementation("me.tbsten.compose.preview.lab:starter:${libs.versions.composePreviewLab.get()}")

            implementation(project(":uiLib"))
        }

        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
        }
    }
}

dependencies {
    val composePreviewLabKspPlugin =
        "me.tbsten.compose.preview.lab:ksp-plugin:${libs.versions.composePreviewLab.get()}"
    add("kspCommonMainMetadata", composePreviewLabKspPlugin)
    add("kspJvm", composePreviewLabKspPlugin)
    add("kspJs", composePreviewLabKspPlugin)
}

composePreviewLab {
    generateFeaturedFiles = true
}

val cleanPreviewLabGallery by tasks.registering(Delete::class) {
    delete(layout.buildDirectory.dir("compose-preview-lab-gallery"))
}

/**
 * Web ドキュメント用に Compose Preview Lab バージョンを TypeScript ファイルとして出力するタスク。
 */
val generateWebDocsLibVersion by tasks.registering {
    // docs プロジェクトのルート（= docs/）
    val docsRoot = rootProject.layout.projectDirectory
    // docs/web/src/generated/libVersion.ts というファイルを生成する
    val outputFile =
        docsRoot
            .dir("web/src/generated")
            .file("libVersion.ts")

    // ルートの libs.versions.composePreviewLab をそのまま利用する
    val version = rootProject.libs.versions.composePreviewLab.get()

    outputs.file(outputFile)

    doLast {
        val file = outputFile.asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // This file is generated by :sample:generateWebDocsLibVersion.
            // DO NOT EDIT MANUALLY.
            export const composePreviewLabVersion = "$version";
            """.trimIndent(),
        )
    }
}

val buildDevelopmentPreviewLabGallery by tasks.registering(Copy::class) {
    dependsOn("jsBrowserDevelopmentExecutableDistribution")
    dependsOn(cleanPreviewLabGallery)
    dependsOn(generateWebDocsLibVersion)

    from(layout.buildDirectory.dir("dist/js/developmentExecutable"))
    into(layout.buildDirectory.dir("web-static-content/compose-preview-lab-gallery"))
}

val buildProductionPreviewLabGallery by tasks.registering(Copy::class) {
    dependsOn("jsBrowserDistribution")
    dependsOn(cleanPreviewLabGallery)
    dependsOn(generateWebDocsLibVersion)

    from(layout.buildDirectory.dir("dist/js/productionExecutable"))
    into(layout.buildDirectory.dir("web-static-content/compose-preview-lab-gallery"))
}
