import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { composePreviewLabVersion } from './src/generated/libVersion';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: 'link',
      label: 'API Reference',
      href: `https://tbsten.github.io/compose-preview-lab/dokka/${composePreviewLabVersion}/core/index.html`,
    },
  ],
};

export default sidebars;
