import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: 'link',
      label: 'API Reference',
      href: 'https://tbsten.github.io/compose-preview-lab/dokka/core/index.html',
    },
  ],
};

export default sidebars;
