package me.tbsten.compose.preview.lab.compiler.compat

import org.jetbrains.kotlin.fir.FirAnnotationContainer
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.declarations.DeprecationsProvider
import org.jetbrains.kotlin.fir.declarations.FirDeclaration
import org.jetbrains.kotlin.fir.expressions.FirAnnotation
import org.jetbrains.kotlin.ir.IrFileEntry
import org.jetbrains.kotlin.ir.builders.IrBuilderWithScope
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueDeclaration
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrFunctionAccessExpression
import org.jetbrains.kotlin.ir.expressions.IrGetValue
import org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression
import org.jetbrains.kotlin.ir.symbols.IrClassSymbol
import org.jetbrains.kotlin.ir.symbols.IrConstructorSymbol
import org.jetbrains.kotlin.ir.symbols.IrFunctionSymbol
import org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.name.Name

/**
 * SPI that absorbs version-specific differences in the Kotlin compiler API.
 *
 * Implementations are registered as a [Factory] in
 * `META-INF/services/.../CompatContext$Factory`, and [CompatContextLoader]
 * picks the best one at runtime based on the current Kotlin compiler version.
 *
 * When a new Kotlin version introduces API drift, add an abstract method here
 * and implement it in each compat module ([Factory.minVersion]).
 */
public interface CompatContext {
    /**
     * Returns whether the FIR declaration is a function.
     *
     * The concrete FIR type used to represent functions has changed across Kotlin versions
     * (e.g. `FirSimpleFunction` vs `FirFunction`); this method abstracts that away.
     */
    public fun isFirFunction(declaration: FirDeclaration): Boolean

    /**
     * Returns the default type of a class symbol.
     *
     * `IrClassifierSymbol.defaultType` (extension) was introduced in 2.2.20; earlier versions
     * only have `IrClass.defaultType` as a direct member property.
     */
    public fun getDefaultType(classSymbol: IrClassSymbol): IrSimpleType

    /**
     * Builds a no-arg annotation from the given constructor symbol and adds it to [function].
     *
     * The IR annotation element type used in [IrSimpleFunction.annotations] has changed
     * across Kotlin versions; this method abstracts the correct construction.
     *
     * **Sample call**:
     * ```kotlin
     * addConstructorCallAnnotation(func, composableType, composableCtorSymbol)
     * ```
     *
     * **Result** (semantically):
     * ```kotlin
     * func.annotations += @Composable  // no-arg annotation
     * ```
     */
    public fun addConstructorCallAnnotation(function: IrSimpleFunction, type: IrType, constructorSymbol: IrConstructorSymbol)

    /**
     * Builds `irCall(callee)` using the version-appropriate IR builder receiver type.
     *
     * In Kotlin 2.2.0 the receiver of [org.jetbrains.kotlin.ir.builders.irCall] was widened
     * from `IrBuilderWithScope` to `IrBuilder`. The main plugin is compiled against the 2.3.x
     * baseline, so its bytecode references `irCall(IrBuilder, ...)`; that signature does not
     * exist in 2.1.x. Each compat module compiles this call against its own Kotlin baseline so
     * the generated bytecode uses the matching JVM signature.
     *
     * **Sample call**: `irCall(builder, myFunSymbol)`
     *
     * **Result** (semantically): `IrCall(symbol = myFunSymbol)` with inferred return type
     */
    public fun irCall(builder: IrBuilderWithScope, callee: IrSimpleFunctionSymbol): IrCall

    /**
     * Builds `irCall(callee, returnType)` using the version-appropriate receiver type.
     * See [irCall] above for the rationale.
     *
     * **Sample call**: `irCall(builder, listOfSymbol, listOfStringType)`
     *
     * **Result** (semantically): `IrCall(symbol = listOfSymbol, returnType = List<String>)`
     */
    public fun irCall(builder: IrBuilderWithScope, callee: IrFunctionSymbol, returnType: IrType): IrFunctionAccessExpression

    /**
     * Builds `irCall(callee, returnType, typeArguments)` using the version-appropriate receiver type.
     * See [irCall] above for the rationale.
     *
     * **Sample call**: `irCall(builder, listOfSymbol, listOfStringType, listOf(stringType))`
     *
     * **Result** (semantically): `IrCall(symbol = listOf<String>, returnType = List<String>,
     * typeArguments = [String])`
     */
    public fun irCall(
        builder: IrBuilderWithScope,
        callee: IrFunctionSymbol,
        returnType: IrType,
        typeArguments: List<IrType>,
    ): IrMemberAccessExpression<*>

    /**
     * Builds `irGet(variable)` using the version-appropriate IR builder receiver type.
     * See [irCall] above for the rationale (same `IrBuilderWithScope` -> `IrBuilder` widening).
     *
     * **Sample call**: `irGet(builder, myValueParam)`
     *
     * **Result** (semantically): `IrGetValue(symbol = myValueParam.symbol)`
     */
    public fun irGet(builder: IrBuilderWithScope, variable: IrValueDeclaration): IrGetValue

    /**
     * Builds `irString(value)` using the version-appropriate IR builder receiver type.
     * See [irCall] above for the rationale (same `IrBuilderWithScope` -> `IrBuilder` widening).
     *
     * **Sample call**: `irString(builder, "hello")`
     *
     * **Result** (semantically): `IrConst(kind = String, value = "hello")`
     */
    public fun irString(builder: IrBuilderWithScope, value: String): IrExpression

    /**
     * Builds a synthetic [IrFileEntry] for synthetic IR files generated by the plugin.
     *
     * `NaiveSourceBasedFileEntryImpl` gained an extra `firstRelevantLineIndex` parameter in
     * Kotlin 2.3, so the bytecode call site differs between 2.1.x / 2.2.x and 2.3.x+.
     * Each compat module emits the call against its own baseline so the JVM signature lines
     * up at runtime.
     */
    public fun createSyntheticFileEntry(fileName: String): IrFileEntry

    /**
     * Returns whether the runtime Kotlin compiler can support KLIB-safe cross-module preview
     * aggregation via FIR-generated synthetic marker classes.
     *
     * `collectAllModulePreviews()` emits per-export marker classes (whose IR is generated by a
     * `FirDeclarationGenerationExtension`) so each hint function gets a unique IdSignature.
     * That requires:
     * - Stable FIR top-level declaration generation (Kotlin 2.3.20+)
     * - JS/Wasm incremental-compile fix from KT-82395 (Kotlin 2.3.21+ / 2.4.0-Beta2+)
     *
     * On older Kotlin versions the plugin reports a compile-time error instead of producing
     * a half-broken aggregation, so users either upgrade or fall back to
     * `collectModulePreviews()` (single-module).
     *
     * Implementations:
     * - `compat-k210` / `compat-k222` / `compat-k2220` / `compat-k230` → `false`
     * - `compat-k2321` (Kotlin 2.3.21+) / `compat-k240_beta2` → `true`
     */
    public fun supportsKlibCrossModuleHint(): Boolean

    /**
     * Returns the [DeprecationsProvider] for [declaration] so the FIR / IDE deprecation
     * cache can be invalidated after a `replaceAnnotations(...)` call.
     *
     * In Kotlin 2.4.0-Beta2 the receiver of `fun getDeprecationsProvider(session)` was
     * narrowed from `FirAnnotationContainer` to `FirCallableDeclaration` /
     * `FirClassLikeDeclaration` (the `FirAnnotationContainer` overload was removed).
     * Implementations dispatch on the concrete declaration type accordingly.
     *
     * Returns null when the declaration is neither a `FirCallableDeclaration` nor a
     * `FirClassLikeDeclaration`; callers skip cache invalidation in that case.
     *
     * **Sample call**: `getDeprecationsProviderCompat(synthesizedFunction, session)`
     *
     * **Result** (semantically): `DeprecationsProvider` whose
     * `getDeprecationsInfo(languageVersionSettings)` reflects the freshly-attached
     * annotation set, or `null` if the receiver type is not supported on this Kotlin
     * version.
     */
    public fun getDeprecationsProviderCompat(declaration: FirAnnotationContainer, session: FirSession): DeprecationsProvider?

    /**
     * Returns the resolved `Boolean` argument named [name] from [annotation], or `null` when
     * the argument is absent or unresolvable.
     *
     * Wraps the stdlib `FirAnnotation.getBooleanArgument` helper, whose signature changed in
     * Kotlin 2.4.0-Beta1: the `session: FirSession` parameter was removed (the helper now
     * reads the resolved name → expression mapping directly off the annotation). The pre-2.4
     * 2-arg form does not exist in 2.4+, and vice versa, so the call has to live in a compat
     * module compiled against the matching baseline.
     *
     * **Sample call**: `getBooleanArgumentCompat(optionAnnotation, IGNORE_NAME, session)`
     *
     * **Result** (semantically): `true` for `@ComposePreviewLabOption(ignore = true)`,
     * `false` for `@ComposePreviewLabOption(ignore = false)`, `null` when the `ignore`
     * argument is omitted or the resolved-arguments mapping is not yet populated.
     */
    public fun getBooleanArgumentCompat(annotation: FirAnnotation, name: Name, session: FirSession): Boolean?

    /**
     * Applies [transformer] to [moduleFragment] using the version-appropriate IR visitor API.
     *
     * The parameter type of `IrElement.transform()` changed in Kotlin 2.1: it moved from
     * `IrElementTransformer<D>` to `IrTransformer<D>`. The compiled call site in the main
     * plugin (baseline 2.3.x) references `IrTransformer`, which does not exist in 2.1.x.
     * This method delegates the call to a compat module compiled against the matching API.
     *
     * [transformer] is typed as [Any] to avoid importing `IrElementTransformerVoid` (or
     * `IrTransformer`) in the interface, which lives in the `compat` module compiled at
     * baseline Kotlin — not at the target runtime version.
     *
     * **Before**: `moduleFragment` with un-transformed IR declarations
     *
     * **After**: same `moduleFragment` with every matching node replaced by [transformer]
     * (e.g. `collectModulePreviews()` call sites replaced with the actual preview list)
     */
    public fun transformModuleFragment(moduleFragment: IrModuleFragment, transformer: Any)

    /**
     * Factory for compat implementations. Each k* module registers its implementation
     * (with its own [minVersion]) in
     * `META-INF/services/me.tbsten.compose.preview.lab.compiler.compat.CompatContext${'$'}Factory`.
     */
    public interface Factory {
        /** The minimum Kotlin version this implementation supports (e.g. "2.3.0", "2.4.0-Beta2"). */
        public val minVersion: String

        /** Creates and returns the [CompatContext] implementation for this factory's [minVersion]. */
        public fun create(): CompatContext
    }

    public companion object {
        /**
         * Loads the [CompatContext] implementation that best matches the current Kotlin compiler version.
         *
         * Among all [Factory] implementations whose [Factory.minVersion] is `<= currentVersion`,
         * picks the one with the largest `minVersion`:
         * ```kotlin
         * val best = factories
         *     .filter { KotlinToolingVersion(it.minVersion) <= currentVersion }
         *     .maxBy { KotlinToolingVersion(it.minVersion) }
         * return best.create()
         * ```
         *
         * For example, when running on Kotlin 2.3.0 with factories for 2.1.0, 2.2.20, and 2.3.0
         * registered, returns the 2.3.0 implementation.
         *
         * @param knownVersion for tests / explicit selection. When null, detected automatically
         *                     from `META-INF/compiler.version` in the compiler JAR.
         */
        public fun load(knownVersion: KotlinToolingVersion? = null): CompatContext = CompatContextLoader.load(knownVersion)
    }
}
