package me.tbsten.compose.preview.lab.compiler.compat

import org.jetbrains.kotlin.fir.declarations.FirDeclaration
import org.jetbrains.kotlin.ir.IrFileEntry
import org.jetbrains.kotlin.ir.builders.IrBuilderWithScope
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueDeclaration
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.IrFunctionAccessExpression
import org.jetbrains.kotlin.ir.expressions.IrGetValue
import org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression
import org.jetbrains.kotlin.ir.symbols.IrClassSymbol
import org.jetbrains.kotlin.ir.symbols.IrConstructorSymbol
import org.jetbrains.kotlin.ir.symbols.IrFunctionSymbol
import org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.IrType

/**
 * SPI that absorbs version-specific differences in the Kotlin compiler API.
 *
 * Implementations are registered as a [Factory] in
 * `META-INF/services/.../CompatContext$Factory`, and [CompatContextLoader]
 * picks the best one at runtime based on the current Kotlin compiler version.
 *
 * When a new Kotlin version introduces API drift, add an abstract method here
 * and implement it in each compat module ([Factory.minVersion]).
 */
public interface CompatContext {
    /**
     * Returns whether the FIR declaration is a function.
     *
     * The concrete FIR type used to represent functions has changed across Kotlin versions
     * (e.g. `FirSimpleFunction` vs `FirFunction`); this method abstracts that away.
     */
    public fun isFirFunction(declaration: FirDeclaration): Boolean

    /**
     * Returns the default type of a class symbol.
     *
     * `IrClassifierSymbol.defaultType` (extension) was introduced in 2.2.20; earlier versions
     * only have `IrClass.defaultType` as a direct member property.
     */
    public fun getDefaultType(classSymbol: IrClassSymbol): IrSimpleType

    /**
     * Builds an annotation from the given constructor symbol and adds it to [function].
     *
     * The IR annotation element type used in [IrSimpleFunction.annotations] has changed
     * across Kotlin versions; this method abstracts the correct construction.
     */
    public fun addConstructorCallAnnotation(function: IrSimpleFunction, type: IrType, constructorSymbol: IrConstructorSymbol)

    /**
     * Builds an annotation with constructor [arguments] and adds it to [function].
     *
     * In Kotlin 2.1–2.3 annotations are positional `IrConstructorCallImpl.arguments[i]`.
     * In Kotlin 2.4 annotations switched to `IrAnnotationImpl.argumentMapping: Map<Name, IrExpression>`.
     * This method abstracts that difference: pass [arguments] in declaration order, the impl
     * resolves parameter names from [constructorSymbol] when needed.
     */
    public fun addConstructorCallAnnotationWithArgs(
        function: IrSimpleFunction,
        type: IrType,
        constructorSymbol: IrConstructorSymbol,
        arguments: List<IrExpression>,
    )

    /**
     * Builds `irCall(callee)` using the version-appropriate IR builder receiver type.
     *
     * In Kotlin 2.2.0 the receiver of [org.jetbrains.kotlin.ir.builders.irCall] was widened
     * from `IrBuilderWithScope` to `IrBuilder`. The main plugin is compiled against the 2.3.x
     * baseline, so its bytecode references `irCall(IrBuilder, ...)`; that signature does not
     * exist in 2.1.x. Each compat module compiles this call against its own Kotlin baseline so
     * the generated bytecode uses the matching JVM signature.
     */
    public fun irCall(builder: IrBuilderWithScope, callee: IrSimpleFunctionSymbol): IrCall

    /**
     * Builds `irCall(callee, returnType)` using the version-appropriate receiver type.
     * See [irCall] above for the rationale.
     */
    public fun irCall(builder: IrBuilderWithScope, callee: IrFunctionSymbol, returnType: IrType): IrFunctionAccessExpression

    /**
     * Builds `irCall(callee, returnType, typeArguments)` using the version-appropriate receiver type.
     * See [irCall] above for the rationale.
     */
    public fun irCall(
        builder: IrBuilderWithScope,
        callee: IrFunctionSymbol,
        returnType: IrType,
        typeArguments: List<IrType>,
    ): IrMemberAccessExpression<*>

    /**
     * Builds `irGet(variable)` using the version-appropriate IR builder receiver type.
     * See [irCall] above for the rationale (same `IrBuilderWithScope` -> `IrBuilder` widening).
     */
    public fun irGet(builder: IrBuilderWithScope, variable: IrValueDeclaration): IrGetValue

    /**
     * Builds `irString(value)` using the version-appropriate IR builder receiver type.
     * See [irCall] above for the rationale (same `IrBuilderWithScope` -> `IrBuilder` widening).
     */
    public fun irString(builder: IrBuilderWithScope, value: String): IrExpression

    /**
     * Builds a synthetic [IrFileEntry] for synthetic IR files generated by the plugin.
     *
     * `NaiveSourceBasedFileEntryImpl` gained an extra `firstRelevantLineIndex` parameter in
     * Kotlin 2.3, so the bytecode call site differs between 2.1.x / 2.2.x and 2.3.x+.
     * Each compat module emits the call against its own baseline so the JVM signature lines
     * up at runtime.
     */
    public fun createSyntheticFileEntry(fileName: String): IrFileEntry

    /**
     * Applies [transformer] to [moduleFragment] using the version-appropriate IR visitor API.
     *
     * The parameter type of `IrElement.transform()` changed in Kotlin 2.1: it moved from
     * `IrElementTransformer<D>` to `IrTransformer<D>`. The compiled call site in the main
     * plugin (baseline 2.3.x) references `IrTransformer`, which does not exist in 2.1.x.
     * This method delegates the call to a compat module compiled against the matching API.
     *
     * [transformer] is typed as [Any] to avoid importing `IrElementTransformerVoid` (or
     * `IrTransformer`) in the interface, which lives in the `compat` module compiled at
     * baseline Kotlin — not at the target runtime version.
     */
    public fun transformModuleFragment(moduleFragment: IrModuleFragment, transformer: Any)

    /**
     * Factory for compat implementations. Each k* module registers its implementation
     * (with its own [minVersion]) in
     * `META-INF/services/me.tbsten.compose.preview.lab.compiler.compat.CompatContext${'$'}Factory`.
     */
    public interface Factory {
        /** The minimum Kotlin version this implementation supports (e.g. "2.3.0", "2.4.0-Beta2"). */
        public val minVersion: String

        public fun create(): CompatContext
    }

    public companion object {
        /**
         * Loads the [CompatContext] implementation that best matches the current Kotlin compiler version.
         *
         * @param knownVersion for tests / explicit selection. When null, detected automatically
         *                     from META-INF/compiler.version.
         */
        public fun load(knownVersion: KotlinToolingVersion? = null): CompatContext = CompatContextLoader.load(knownVersion)
    }
}
