@file:OptIn(ExperimentalComposePreviewLabApi::class)

package me.tbsten.compose.preview.lab

import javax.inject.Inject
import org.gradle.api.Action
import org.gradle.api.Project
import org.gradle.api.model.ObjectFactory
import org.gradle.kotlin.dsl.getValue
import org.gradle.kotlin.dsl.property
import org.gradle.kotlin.dsl.provideDelegate
import org.gradle.kotlin.dsl.setValue

/**
 * `composePreviewLab { ... }` DSL block. Applied in build.gradle.kts:
 *
 * ```kotlin
 * composePreviewLab {
 *     generatePackage = "myModule"
 *     generateFeaturedFiles = true
 *     collectPreviews {
 *         enabled = false
 *     }
 * }
 * ```
 */
abstract class ComposePreviewLabExtension @Inject constructor(objects: ObjectFactory, project: Project) {
    /**
     * Package where PreviewList / PreviewAllList objects are generated. Defaults to a
     * camelCase version of the project name (e.g. "my-app" → "myApp").
     */
    var generatePackage: String by objects.property<String>()
        .convention(
            project.name
                .split(Regex("(\\.)|_|-"))
                .mapIndexed { index, word -> if (index == 0) word else word.replaceFirstChar { it.uppercase() } }
                .joinToString(""),
        )

    /**
     * Used to resolve relative file paths in generated previews. Defaults to the root
     * project directory.
     */
    var projectRootPath: String by objects.property<String>()
        .convention(project.rootProject.projectDir.absolutePath)

    /**
     * When true, scans the `.composepreviewlab/featured/` directory and generates a
     * FeaturedFileList map grouping file paths by directory name. Defaults to false.
     */
    var generateFeaturedFiles: Boolean by objects.property<Boolean>()
        .convention(false)

    /**
     * Per-module configuration for the per-declaration preview hint pipeline. See
     * [CollectPreviewsConfig] for the full set of options; the most common use is
     * `enabled = false` to keep sample / test-fixture module previews out of downstream
     * consumers' `collectAllModulePreviews()` while making local collect call-sites a
     * compile-time error.
     */
    val collectPreviews: CollectPreviewsConfig = objects.newInstance(CollectPreviewsConfig::class.java)

    /** Kotlin-DSL friendly accessor for [collectPreviews]. */
    fun collectPreviews(action: Action<CollectPreviewsConfig>) {
        action.execute(collectPreviews)
    }
}

/**
 * Configures the per-declaration preview hint pipeline for one module.
 *
 * ```kotlin
 * composePreviewLab {
 *     collectPreviews {
 *         enabled = false
 *     }
 * }
 * ```
 */
abstract class CollectPreviewsConfig @Inject constructor(objects: ObjectFactory) {
    /**
     * Whether this module participates in per-declaration preview hint emission.
     *
     * - `true` (default) — `@Preview` functions emit a marker interface and a
     *   `previewHint_<scope>(...)` overload, so they can be discovered cross-module by
     *   `collectAllModulePreviews()` consumers.
     * - `false` — no marker / hint pair is emitted, **and** any
     *   `collect[All]ModulePreviews()` call site in the same module becomes a compile-time
     *   error. Use for sample / test-fixture modules whose previews must never leak
     *   downstream.
     *
     * **Caveat — Binary Compatibility Validator**: flipping `true` → `false` removes every
     * synthesized hint from generated bytecode. Hints carry `@InternalComposePreviewLabApi`,
     * so projects that list that marker in `apiValidation { nonPublicMarkers }` (recommended;
     * see this project's root `build.gradle.kts`) are ABI-neutral when toggling. Otherwise
     * add the marker or re-dump baselines once via `./gradlew apiDump`.
     */
    var enabled: Boolean by objects.property<Boolean>()
        .convention(true)

    /**
     * Module-level default scope for `@Preview` hints emitted from this module. The compiler
     * plugin substitutes any `@ComposePreviewLabOption(collectScopes = [...])` /
     * `collect[All]ModulePreviews(scope = ...)` value of
     * `ComposePreviewLabOption.DefaultCollectScope` with this string before embedding it
     * into the synthetic `previewHint_<scope>` function name. Typical use — pin a library's
     * previews to a library-specific bucket so they do not leak into a consumer app:
     *
     * ```kotlin
     * // uiLib/build.gradle.kts
     * composePreviewLab {
     *     collectPreviews {
     *         defaultCollectScope = "acme_ui"
     *     }
     * }
     * ```
     *
     * Defaults to `"default"`. The value must match `[A-Za-z0-9_]+` because it is embedded
     * into a Kotlin identifier; invalid values are rejected by the compiler plugin's
     * command-line processor.
     *
     * **Experimental** — part of the stabilizing `collectScopes` design. See
     * [annotation/docs/collect-scopes.md](https://github.com/TBSten/compose-preview-lab/blob/main/annotation/docs/collect-scopes.md)
     * for the full design rationale and the opt-in propagation semantics across Gradle DSL
     * → annotation → call-site.
     */
    @ExperimentalComposePreviewLabApi
    var defaultCollectScope: String by objects.property<String>()
        .convention(ComposePreviewLabOption.DefaultCollectScope)
}
